services:
  frontend:
    build:
      context: ../frontend  
      dockerfile: Dockerfile 
    ports:
      - "80:80"             
    networks:
      - app-network
    volumes:
      - ../frontend:/app    

  backend:
    build:
      context: ../backend             
      dockerfile: Dockerfile  
    ports:
      - "8080:8080"     
    
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
